version: '3.8'

services:
  metacline:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - supabase
      - n8n

  supabase:
    image: supabase/supabase-db:latest
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=metacline_dev
    volumes:
      - supabase_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=metacline
      - N8N_BASIC_AUTH_PASSWORD=development
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  supabase_data:
  n8n_data: 